### ISSUE TITLE
Issue with multiple ports

### ISSUE THREAD

**Issue by sardaukar** [YuukanOO/seelf#71]
I skipped v2.2 (was waiting on private registries) and my go-to example app to test multiple ports is [Forgejo], the Gitea fork I use. It has an HTTP and a TCP port for the built-in SSH server for git cloning.

Here is the `compose.yaml` I use with my current Docker UI:

```
services:

  app:
    image: codeberg.org/forgejo/forgejo:7.0.3
    environment:
      - USER_UID=1026
      - USER_GID=100
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
    networks:
      - dockge_default
    volumes:
      - /volume1/docker/compose/data/forgejo/data:/data
    ports:
      - 10022:10022
    depends_on:
      db:
        condition: service_healthy
    labels:
      traefik.enable: "true"
      traefik.http.routers.forgejo.rule: "Host(`forgejo.my.redacted.domain`)"
      traefik.http.routers.forgejo.service: "forgejo"
      traefik.http.routers.forgejo.entrypoints: "https"
      traefik.http.routers.forgejo.tls.certresolver: "gandi"
      traefik.http.routers.forgejo.tls.domains[0].main: "my.redacted.domain"
      traefik.http.routers.forgejo.tls.domains[0].sans: "*.my.redacted.domain"
      traefik.http.services.forgejo.loadbalancer.server.port: "3000"

  db:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    networks:
      - dockge_default
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U forgejo -d forgejo']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - /volume1/docker/compose/data/forgejo/postgres:/var/lib/postgresql/data

networks:
  dockge_default:
    external: true

x-dockge:
  urls:
    - https://forgejo.my.redacted.domain
```

I only specify the SSH port I use (10022, to avoid taking the default 22) and the 3000 port for the app is part of the Traefik labels I add.

I tried the following compose with Seelf:

```
services:

  app:
    image: codeberg.org/forgejo/forgejo:7.0.3
    environment:
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
    volumes:
      - forgejo-data:/data
    ports:
      - 3000:3000
      - 10022:10022/tcp
    depends_on:
      db:
        condition: service_healthy
   
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U forgejo -d forgejo']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - forgejo-postgres:/var/lib/postgresql/data

volumes:
  forgejo-data:
  forgejo-postgres:

```

Then I go to the install, make sure the HTTP port is 3000 and SSH is 10022, and install. Then create a new user (becomes the admin), add my SSH key to the settings and create a repo. Cloning it via HTTP works, but via SSH it just hangs, presumably because the TCP port has a mismatch. And sure enough, the app info on Seelf's UI shows that port `10022` is... wrong?

![annotely_image](https://github.com/YuukanOO/seelf/assets/153407/ca94ade8-7517-4b5a-b5f0-a60c9b935887)

Not sure why I'm getting port `32773` instead of the requested `10022`. The docs don't explain this, I think?

Thanks for any pointers!

[Forgejo]: https://forgejo.org/
