### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by decryptedchaos** [YuukanOO/seelf#88]
After six hours of tinkering i can only conclude this is woefully broken?  Firstly even just exposed directly via port 8080 the thing doesn't work it wont accept the login defined in the envar HTTP 400 error  

Beyond that, it seems the traefik integration is also broken? i ended up rolling my own traefik config to work around it,  but your claim of painless is lacking..   

I've had enough of trying to make it work for now,  ask me for what would be helpful and i'll try to provide it tomorrow.

**Comment by YuukanOO** [comment]
Could you please provide more informations such as the installation method?

**Comment by decryptedchaos** [comment]
> Could you please provide more informations such as the installation method?

It is deployed via docker compose using the following (slightly modified for my own traefik workaround 

```
services:
  web:
    restart: unless-stopped
    image: yuukanoo/seelf:2.4.0 
    container_name: seelf
    environment:
      - ADMIN_EMAIL=redacted-email # Its set correctly 
      - ADMIN_PASSWORD=redacted-password # as shown here
      - EXPOSED_ON=http://seelf@mydomain.tld # <- I've done it this way
      - EXPOSED_ON=http://seelf@docker.localhost # <- I've done it this way as a test
      - HTTP_SECURE= # Force fallback to the default handling of http secure (based on EXPOSED_ON if set)
   # ports:
   #   - "8080:8080"
    labels:
      - app.seelf.exposed=true
      - app.seelf.subdomain=seelf
      - subdomain=seelf # this is my workaround for a standalone traefik
      - domain=mydomain.tld # also my work around
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh:/root/.ssh 
      - data:/seelf/data 
    networks:
      - proxy

networks:
  proxy:
    external: true
volumes:
  ssh:
  data:

```

> The account details provided in the environment is only used to create the first account. Once the first account has been set up, if you want to change the admin password, you must use the profile page.

Right, but since it wont accept the one i supply in the compose file i can never login in the first place. 

This is what i get in the browser console: 

![Image](https://github.com/user-attachments/assets/63363865-e504-476b-9e38-cebd035f1e9e)


> The traefik part is deployed only when [creating a target](https://yuukanoo.github.io/seelf/reference/targets.html) or when [exposing seelf using a local target](https://yuukanoo.github.io/seelf/guide/installation.html#exposing-seelf).

Yes as you can see i've done this and it does NOT work,  it never exposes itself..

**Comment by YuukanOO** [comment]
Could you start from scratch by doing a `docker compose down --volumes` to make sure **volumes are completely removed** and then trying with something along the lines:

```yml
services:
  web:
    restart: unless-stopped
    image: yuukanoo/seelf:2.4.0
    container_name: seelf
    environment:
      - ADMIN_EMAIL=your-email
      - ADMIN_PASSWORD=your-password
      - EXPOSED_ON=http://seelf@your-domain.tld
      - HTTP_SECURE=
    labels: 
      - app.seelf.exposed=true
      - app.seelf.subdomain=seelf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh:/root/.ssh
      - data:/seelf/data

volumes:
  ssh:
  data:
```
